  $(call log.debug, COOKBOOK BEGIN INCLUDE: cookbook/input_paths_lingproc.mk)

# The input bucket
IN_S3_BUCKET_PROCESSED_DATA_LINGPROC ?= 42-processed-data-final
  $(call log.debug, IN_S3_BUCKET_PROCESSED_DATA_LINGPROC)

IN_PROCESS_LABEL_LINGPROC ?= lingproc
  $(call log.debug, IN_PROCESS_LABEL_LINGPROC)

IN_PROCESS_SUBTYPE_LABEL_LINGPROC ?=
  $(call log.debug, IN_PROCESS_SUBTYPE_LABEL_LINGPROC)
  
IN_TASK_LINGPROC ?= pos
  $(call log.debug, IN_TASK_LINGPROC)

IN_MODEL_ID_LINGPROC ?= spacy_v3.6.0-multilingual
  $(call log.debug, IN_MODEL_ID_LINGPROC)

IN_RUN_VERSION_LINGPROC ?= v1-0-3
  $(call log.debug, IN_RUN_VERSION_LINGPROC)
  
IN_RUN_ID_LINGPROC ?= $(IN_PROCESS_LABEL_LINGPROC)-$(IN_TASK_LINGPROC)-$(IN_MODEL_ID_LINGPROC)_$(IN_RUN_VERSION_LINGPROC)
  $(call log.debug, IN_RUN_ID_LINGPROC)
  
# The s3 input path
IN_S3_PATH_PROCESSED_DATA_LINGPROC := s3://$(IN_S3_BUCKET_PROCESSED_DATA_LINGPROC)/$(IN_PROCESS_LABEL_LINGPROC)$(IN_PROCESS_SUBTYPE_LABEL_LINGPROC)/$(IN_RUN_ID_LINGPROC)/$(NEWSPAPER)
  $(call log.debug, IN_S3_PATH_PROCESSED_DATA_LINGPROC)

# The local path in BUILD_DIR
IN_LOCAL_PATH_PROCESSED_DATA_LINGPROC := $(BUILD_DIR)/$(IN_S3_BUCKET_PROCESSED_DATA_LINGPROC)/$(IN_PROCESS_LABEL_LINGPROC)$(IN_PROCESS_SUBTYPE_LABEL_LINGPROC)/$(IN_RUN_ID_LINGPROC)/$(NEWSPAPER)
  $(call log.debug, IN_LOCAL_PATH_PROCESSED_DATA_LINGPROC)



 $(call log.debug, COOKBOOK END INCLUDE: cookbook/input_paths_lingproc.mk)
