$(call log.debug, COOKBOOK BEGIN INCLUDE: cookbook/output_paths_topics.mk)


MALLET_RANDOM_SEED ?= 42
  $(call log.debug, MALLET_RANDOM_SEED)


# The output bucket
OUT_S3_BUCKET_PROCESSED_DATA_TOPICS ?= 41-processed-data-staging
$(call log.debug, OUT_S3_BUCKET_PROCESSED_DATA_TOPICS)


OUT_PROCESS_LABEL_TOPICS ?= topics
  $(call log.debug, OUT_PROCESS_LABEL_TOPICS)

OUT_PROCESS_RUN_VERSION_TOPICS ?= v2-0-1
  $(call log.debug, OUT_PROCESS_RUN_VERSION_TOPICS)

OUT_PROCESSED_TASK_TOPICS ?= tm
  $(call log.debug, OUT_PROCESSED_TASK_TOPICS)

OUT_PROCESSED_MODEL_SPECIFICITY_TOPICS ?= mallet_infer_seed$(MALLET_RANDOM_SEED)
  $(call log.debug, OUT_PROCESSED_MODEL_SPECIFICITY_TOPICS)

OUT_PROCESSED_MODEL_VERSION_TOPICS ?= v2.0.1
  $(call log.debug, OUT_PROCESSED_MODEL_VERSION_TOPICS)

OUT_PROCESSED_LANG_TOPICS ?= multilingual
  $(call log.debug, OUT_PROCESSED_LANG_TOPICS)

OUT_PROCESSED_MODEL_ID_TOPICS ?= $(OUT_PROCESSED_TASK_TOPICS)-$(OUT_PROCESSED_MODEL_SPECIFICITY_TOPICS)_$(OUT_PROCESSED_MODEL_VERSION_TOPICS)-$(OUT_PROCESSED_LANG_TOPICS)
  $(call log.debug, OUT_PROCESSED_MODEL_ID_TOPICS)

OUT_PROCESSED_RUN_ID_TOPICS ?= $(OUT_PROCESS_LABEL_TOPICS)-$(OUT_PROCESSED_MODEL_ID_TOPICS)_$(OUT_PROCESS_RUN_VERSION_TOPICS)
  $(call log.debug, OUT_PROCESSED_RUN_ID_TOPICS)

OUT_S3_PATH_PROCESSED_DATA_TOPICS := s3://$(OUT_S3_BUCKET_PROCESSED_DATA_TOPICS)/$(OUT_PROCESS_LABEL_TOPICS)/$(OUT_PROCESSED_RUN_ID_TOPICS)/$(NEWSPAPER)
  $(call log.debug, OUT_S3_PATH_PROCESSED_DATA_TOPICS)

OUT_LOCAL_PATH_PROCESSED_DATA_TOPICS := $(BUILD_DIR)/$(OUT_S3_BUCKET_PROCESSED_DATA_TOPICS)/$(OUT_PROCESS_LABEL_TOPICS)/$(OUT_PROCESSED_RUN_ID_TOPICS)/$(NEWSPAPER)
  $(call log.debug, OUT_LOCAL_PATH_PROCESSED_DATA_TOPICS)



$(call log.debug, COOKBOOK END INCLUDE: cookbook/output_paths_topics.mk)
